sudo: required
services:
  - docker

before_install:
  - docker build  -t ionbcreative/docker-react -f Dockerfile.dev .

script:
  - docker run ionbcreative/docker-react npm run test -- --coverage

language: generic
